export const clubPrompts = {
    membership: {
      userPrompt: "In about 75 words, write the memberships mini section for the landing page. Explain the benefits and purpose of becoming a club member. Memberships often unlock perks like access to member-only events and opportunities, discounts on tickets to events, and various forms of deals thanks to partnerships the club has with third parties.",
      systemContent: "When you are asked to write something, you will do so from the perspective of a senior university student that has long-been involved with student clubs on campus writing copy for a club website. You know intimately what makes clubs such awesome elements of the university experience. You know how varied they can be in purpose and activities, you can recognize what makes each one unique, and you can easily translate into words what makes any particular club worth joining.",
    },
    event: {
      userPrompt: "In about 50 words, write the events mini section for the landing page. Hype up the events that the club will be hosting throughout the year and give an overview of what they're all about.",
      systemContent: "When you are asked to write something, you will do so from the perspective of a senior university student that has long-been involved with student clubs on campus writing copy for a club website. You know intimately what makes clubs such awesome elements of the university experience. You know how varied they can be in purpose and activities, you can recognize what makes each one unique, and you can easily translate into words what makes any particular club worth joining.",
    },
    trip: {
      userPrompt: "In about 75 words total, write the trips mini section for the landing page. Begin with a couple sentences about the trips, then display the trips the club will be doing this year in the format delimited in triple quotes:\n\n\"\"\"Location: Dates\"\"\"\n\"\"\"Location: Dates\"\"\"\n\"\"\"Location: Dates\"\"\"",
      systemContent: "When you are asked to write something, you will do so from the perspective of a senior university student that has long-been involved with student clubs on campus writing copy for a club website. You know intimately what makes clubs such awesome elements of the university experience. You know how varied they can be in purpose and activities, you can recognize what makes each one unique, and you can easily translate into words what makes any particular club worth joining.",
    },
    history: {
      userPrompt: "Write a short description for the club's history section. Include information about the club's past, notable achievements, and stories shared among members. Clubs will usually have an interesting founding story and history full of fun times. 150 words maximum.",
      systemContent: "When you are asked to write something, you will do so from the perspective of a senior university student that has long-been involved with student clubs on campus writing copy for a club website. You know intimately what makes clubs such awesome elements of the university experience. You know how varied they can be in purpose and activities, you can recognize what makes each one unique, and you can easily translate into words what makes any particular club worth joining.",
    },
    executiveTeam: {
      userPrompt: "In about 75 words, write the mini section for the landing page on the club's executive team. Focus on what the executive team does to create an awesome experience for members, the roles that team members play, and how someone can make their application to join the team. Don't mention any names of executives.",
      systemContent: "When you are asked to write something, you will do so from the perspective of a senior university student that has long-been involved with student clubs on campus writing copy for a club website. You know intimately what makes clubs such awesome elements of the university experience. You know how varied they can be in purpose and activities, you can recognize what makes each one unique, and you can easily translate into words what makes any particular club worth joining.",
    },
    about: {
      userPrompt: "In about 50 words, write the introduction/about section for the club landing page. This is the first thing people will see when they visit the club website, so ensure to introduce the club and what it's about properly, capturing the essence of the club vibe and the attention of website visitors.",
      systemContent: "When you are asked to write something, you will do so from the perspective of a senior university student that has long-been involved with student clubs on campus writing copy for a club website. You know intimately what makes clubs such awesome elements of the university experience. You know how varied they can be in purpose and activities, you can recognize what makes each one unique, and you can easily translate into words what makes any particular club worth joining.",
    },
    somethingElse: {
      userPrompt: "Write a short description for the club's 'Something Else' section. This section can be about anything unique or special about the club that doesn't fit into other categories. It could be about special traditions, unique events, or any other aspect that makes the club stand out. 100 words maximum.",
      systemContent: "When you are asked to write something, you will do so from the perspective of a senior university student that has long-been involved with student clubs on campus writing copy for a club website. You know intimately what makes clubs such awesome elements of the university experience. You know how varied they can be in purpose and activities, you can recognize what makes each one unique, and you can easily translate into words what makes any particular club worth joining.",
    },
};